name: dart_dependency_checker_samples

environment:
  sdk: ^3.6.0

dependencies:
  # some comment that will be removed
  meta: ^1.11.0

  args: 2.4.2

#  some_hosted_source:
#    hosted: https://some-package-server.com
#    version: ^1.2.0
  some_hosted_source:
    hosted:   https://some-package-server.com
    version: ^1.4.0
  flutter:
    sdk: flutter
  some_path_source:
    path:   ../some_path_dependency

  some_path_source2:
    path: ../some_path_dependency2
  equatable: ^2.0.7

  window_size:
    git:
      url: git@github.com:google/flutter-desktop-embedding.git
      ref: e48abe7c3e9ebfe0b81622167c5201d4e783bb81
      path: plugins/window_size


  yaansi:
    git: https://github.com/akaiser/yaansi.git
  path: ^1.9.1

  yaml: 3.1.3

dev_dependencies:

  test:    ^1.25.0

  integration_test:
    sdk: any
  lints:  3.0.0
  
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

