name: example
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.2.0

dependencies:
  dart_dependency_checker:
    path: ../

dev_dependencies:
  lints: ^3.0.0
