name: dart_dependency_checker
description: A utility package for checking and fixing dependencies within Dart/Flutter packages.
repository: https://github.com/akaiser/dart_dependency_checker
version: 1.0.6

platforms:
  linux:
  macos:
  windows:

environment:
  sdk: ^3.6.0

dependencies:
  equatable: ^2.0.7
  path: ^1.9.1
  yaml: ^3.1.3

dev_dependencies:
  lints: ^5.1.1
  test: ^1.26.3
