name: dart_dependency_checker
description: Checks for unused dependencies
repository: https://github.com/akaiser/dart_dependency_checker
version: 0.0.1

executables:
  dart_dependency_checker:

environment:
  sdk: ^3.2.0

dependencies:
  dart_console: ^1.2.0
  pubspec_yaml: ^3.1.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9
