name: dart_dependency_checker
description: Checks declared but unused dependencies within Dart/Flutter packages.
repository: https://github.com/akaiser/dart_dependency_checker
version: 0.0.1

executables:
  dart_dependency_checker:

environment:
  sdk: ^3.2.0

dependencies:
  args: ^2.4.2
  equatable: ^2.0.5
  yaml: ^3.1.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9
