name: dart_dependency_checker
description: A utility package for checking dependencies within Dart/Flutter packages.
repository: https://github.com/akaiser/dart_dependency_checker
version: 0.3.2

platforms:
  linux:
  macos:
  windows:

environment:
  sdk: ^3.6.0

dependencies:
  equatable: ^2.0.7
  yaml: ^3.1.3

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
