name: Pull Request

on: [ pull_request ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-dart
      - run: dart pub get

  analyze:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - run: dart analyze
      - run: dart format -o none --set-exit-if-changed .

  test:
    needs: analyze
    runs-on: ubuntu-latest
    steps:
      - run: dart test
